#!/usr/bin/env python3
"""
Build a per-archive image library + layout JSON for one (config, seed) pair,
for the blog post's "click again to zoom to native" view.

For one archive run we emit, under <ASSETS>/<arc>_s<N>_lib/:
  thumbs/img_NNNNNN.webp  -- 3000+ color WebP thumbs, one per published image (--grayscale to flatten)
  layout.json             -- per-image (row, col) for {chronological, siglip}
                             plus the dims of each grid

The chronological layout is read from <run>/archive/archive_grid.json (already
generated by the eval pipeline). The SigLIP layout is re-derived from the
cached SigLIP-2 embeddings under <run>/embeddings_openclip_SigLIP2-B-alignet.npz
by running umap.UMAP() (matching the params in embed_and_visualize.py) and
then snapping with rasterfairy <https://github.com/Quasimondo/RasterFairy>.

Prototype: this is currently called only for default_s4 to validate the UX.
If it works we'll loop over the other 41 (config, seed) pairs.

Usage:
    python tools/build_archive_image_lib.py default_s4
    python tools/build_archive_image_lib.py default_s4 --force
"""
from __future__ import annotations

import argparse
import importlib
import io
import json
import sys
from pathlib import Path

import numpy as np
from PIL import Image

# umap + rasterfairy are imported LAZILY (only for the SigLIP layout) — they pull
# in scipy/numba and can fail to import under a mismatched numpy, which must not
# block runs that have no embeddings (SigLIP is optional; the gallery greys it out).
def _prep_rasterfairy() -> None:
    """rasterfairy doesn't fully self-init under modern numpy; replicate the dance
    from embed_and_visualize.py: (a) attach the `prime` submodule onto the
    rasterfairy.rasterfairy module (its code references `prime.Prime()` without
    importing it), and (b) restore deprecated numpy aliases the library still uses."""
    rf_module = importlib.import_module("rasterfairy.rasterfairy")
    prime_module = importlib.import_module("rasterfairy.prime")
    rf_module.prime = prime_module
    for alias, t in (("float", float), ("int", int), ("bool", bool)):
        if not hasattr(np, alias):
            setattr(np, alias, t)


REPO = Path("/home/jupyter-smearle/picbreeder-vlm")
SWEEP = REPO / "sweep_logs" / "sweep"

sys.path.insert(0, str(Path(__file__).parent))
from hf_archive_push import parse_config, parse_arc, canonical_arc   # noqa: E402  (run-name -> config/arc)
ASSETS = Path("/home/jupyter-smearle/smearle.github.io/picbreeder-vlm-06b0d76d/assets/archives")

# Same arc -> sweep-dir-basename map used by build_blog_archive_assets.py.
ARC_TO_RUN = {
    "default":     "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_nopersonalities_fixed-sesh",
    "noise_0.05":  "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_randp0.05_rmode-all_nopersonalities_fixed-sesh",
    "noise_0.25":  "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_randp0.25_rmode-all_nopersonalities_fixed-sesh",
    "noise_0.5":   "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_randp0.5_rmode-all_nopersonalities_fixed-sesh",
    "noise_0.75":  "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_randp0.75_rmode-all_nopersonalities_fixed-sesh",
    "noise_1.0":   "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_randp1_rmode-all_nopersonalities_fixed-sesh",
    "mem_0":       "th0_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_nopersonalities_fixed-sesh",
    "mem_2":       "th2_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_nopersonalities_fixed-sesh",
    "mem_10":      "th10_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_nopersonalities_fixed-sesh",
    "mem_20":      "th-1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_nopersonalities_fixed-sesh",
    "agents_10":   "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_nopersonalities_traits10_fixed-sesh",
    "agents_100":  "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_nopersonalities_traits100_fixed-sesh",
    "agents_1000": "th1_ag20_model-gemini-2.5-pro_tb-1_scheme-toggle_nopersonalities_traits1000_fixed-sesh",
    "random":      "ag20_tb-1_scheme-toggle_randp2_rmode-all_nopersonalities_fixed-sesh",
}


def parse_arc_seed(token: str) -> tuple[str, int]:
    """'default_s4' -> ('default', 4)."""
    if "_s" not in token:
        raise SystemExit(f"expected '<arc>_s<seed>', got {token!r}")
    arc, s = token.rsplit("_s", 1)
    return arc, int(s)


def chronological_layout(grid_json: Path) -> tuple[list[list[int]], list[int], int]:
    """Read the existing archive_grid.json and convert each bbox to (row, col).

    bbox is [x1, y1, x2, y2] in pixels in the rendered grid PNG; thumb_size and
    margin live at the top of the file. row = (y1 - margin) / (thumb + margin).

    Returns (rc, dims=[rows, cols], n) where rc[i] is the (row, col) of the i'th
    image (in publication order). Filenames are derived externally:
    image_i corresponds to img_{i+1:06d}.png.
    """
    d = json.loads(grid_json.read_text())
    thumb = int(d["thumb_size"])
    margin = int(d["margin"])
    step = thumb + margin
    # Entries are NOT guaranteed to be sorted by `index`; sort first.
    entries = sorted(d["entries"], key=lambda e: e["index"])
    rc: list[list[int]] = []
    max_r = max_c = 0
    for e in entries:
        x1, y1, _, _ = e["bbox"]
        c = (int(x1) - margin) // step
        r = (int(y1) - margin) // step
        rc.append([r, c])
        max_r = max(max_r, r)
        max_c = max(max_c, c)
    return rc, [max_r + 1, max_c + 1], len(rc)


def siglip_layout(npz_path: Path, n_keep: int) -> tuple[list[list[int]], list[int]]:
    """Re-derive the SigLIP-sorted grid from cached embeddings.

    n_keep: limit to the first n_keep filenames so both layouts cover the same
    image set (the chronological grid is sometimes rendered before the final
    one or two images are published, leaving a tiny tail in the embeddings).
    """
    import umap                       # lazy: scipy/numba heavy, only needed here
    import rasterfairy                 # noqa: F401  (used via transformPointCloud2D)
    _prep_rasterfairy()
    d = np.load(npz_path, allow_pickle=True)
    fns = list(d["filenames"])
    emb = np.asarray(d["embeddings"], dtype=np.float32)
    if len(fns) > n_keep:
        print(f"  trimming embeddings {emb.shape[0]} -> {n_keep} to match chronological set")
        # Assume filenames are in published order, same as chronological indexing.
        emb = emb[:n_keep]
    print(f"  running UMAP on {emb.shape} ...")
    reducer = umap.UMAP(n_components=2, random_state=0)
    coords = reducer.fit_transform(emb)
    print(f"  rasterfairy on {coords.shape} ...")
    grid_points, dims = rasterfairy.transformPointCloud2D(
        np.asarray(coords, dtype=float))
    grid_positions = np.rint(np.asarray(grid_points, dtype=float)).astype(int)
    # rasterfairy returns dims as (cols, rows) and positions as (col, row).
    cols, rows = int(dims[0]), int(dims[1])
    rc = [[int(r), int(c)] for c, r in grid_positions.tolist()]
    return rc, [rows, cols]


# ---------------------------------------------------------------------------
# Lineage-derived layouts (branched grid, ratings grid, radial phylogeny).
# All three key off the archive's parent links (source_entry_ids). Image i
# (0-based) is the published entry with id == f"img_{i+1:06d}".
# ---------------------------------------------------------------------------
def _aligned_entries(metadata_path: Path, n: int) -> list[dict]:
    """Return entries[0..n) aligned so index i is the entry id img_{i+1:06d}."""
    es = json.loads(metadata_path.read_text())["entries"]
    by_id = {e.get("id"): e for e in es}
    return [by_id.get(f"img_{i + 1:06d}", {}) for i in range(n)]


def _build_forest(entries: list[dict], n: int):
    """Primary-parent tree over the first n entries.

    Returns (children, roots): children[i] = list of child indices (primary
    parent = earliest-published parent, matching the coloring tree elsewhere).
    """
    id_to_idx = {f"img_{i + 1:06d}": i for i in range(n)}
    primary = [None] * n
    for i, e in enumerate(entries):
        ps = []
        for sid in (e.get("source_entry_ids") or []):
            j = id_to_idx.get(str(sid))
            if j is not None and j != i:
                ps.append(j)
        if ps:
            primary[i] = min(ps)              # earliest-published parent
    children: list[list[int]] = [[] for _ in range(n)]
    for i, p in enumerate(primary):
        if p is not None:
            children[p].append(i)
    roots = [i for i, p in enumerate(primary) if p is None]
    return children, roots


def _subtree_leaves(children, roots, n) -> list[int]:
    """Leaf-count of each node's subtree (iterative post-order; deep trees ok)."""
    leaf = [0] * n
    for root in roots:
        stack = [(root, False)]
        while stack:
            node, done = stack.pop()
            if done:
                cs = children[node]
                leaf[node] = sum(leaf[c] for c in cs) if cs else 1
            else:
                stack.append((node, True))
                for c in children[node]:
                    stack.append((c, False))
    return leaf


def _grid_from_order(order: list[int], n: int, cols: int) -> dict:
    """Snap a 1-D ordering of image indices into a row-major grid of `cols`."""
    rc: list[list[int]] = [[0, 0]] * n
    for pos, i in enumerate(order):
        rc[i] = [pos // cols, pos % cols]
    rows = (n + cols - 1) // cols
    return {"dims": [rows, cols], "rc": rc}


def _branch_count(entries, n) -> list[int]:
    """Number of published children per node ("how branched" each image is).

    Prefers the entry's own ``n_published_children`` (counts every published
    child regardless of which parent is primary); falls back to the in-range
    primary-parent child count from the lineage forest.
    """
    children, _roots = _build_forest(entries, n)
    counts = [0] * n
    for i in range(n):
        npc = entries[i].get("n_published_children")
        counts[i] = int(npc) if isinstance(npc, int) else len(children[i])
    return counts


def branched_layout(entries, n, cols) -> dict:
    """Grid ranked by branch count, most-branched first.

    "Most Branched" = the images that spawned the most published children,
    descending. Ties broken by publication order (earliest first) so the grid
    is stable run-to-run.
    """
    counts = _branch_count(entries, n)
    order = sorted(range(n), key=lambda i: (-counts[i], i))
    return _grid_from_order(order, n, cols)


def ratings_layout(entries, n, cols) -> dict:
    """Grid ordered by descending mean VLM rating (un-rated images last)."""
    def rate(e):
        vr = e.get("vlm_ratings") or []
        return sum(vr) / len(vr) if vr else -1.0
    order = sorted(range(n), key=lambda i: (-rate(entries[i]), i))
    return _grid_from_order(order, n, cols)


def _normalize_xy(raw) -> list:
    """Center + uniformly scale [x,y] points into the unit square (aspect kept)."""
    xs = [p[0] for p in raw]; ys = [p[1] for p in raw]
    cx = (min(xs) + max(xs)) / 2.0; cy = (min(ys) + max(ys)) / 2.0
    span = max(max(xs) - min(xs), max(ys) - min(ys)) or 1.0
    return [[round(0.5 + (x - cx) / span, 5), round(0.5 + (y - cy) / span, 5)] for x, y in raw]


def _radial_scatter_xy(children, roots, leaf, n) -> list:
    """Analytic radial 'tree of life': depth -> radius, leaf-count -> angular wedge."""
    import math
    xy = [None] * n
    total = sum(leaf[r] for r in roots) or 1
    queue = []; a = 0.0
    for r in sorted(roots):                            # roots on ring 1 (center free)
        w = 2 * math.pi * (leaf[r] / total)
        queue.append((r, a, a + w, 1)); a += w
    head = 0
    while head < len(queue):
        i, a0, a1, d = queue[head]; head += 1
        ang = (a0 + a1) / 2.0
        xy[i] = [d * math.cos(ang), d * math.sin(ang)]
        cs = sorted(children[i])
        if cs:
            tot = sum(leaf[c] for c in cs) or 1
            aa = a0
            for c in cs:
                w = (a1 - a0) * (leaf[c] / tot)
                queue.append((c, aa, aa + w, d + 1)); aa += w
    for i in range(n):
        if xy[i] is None:
            xy[i] = [0.0, 0.0]
    return _normalize_xy(xy)


def _graphviz_scatter_xy(children, roots, n, engine):
    """Node positions from a graphviz engine (twopi=radial rings spread by Prism
    overlap-removal, sfdp=scalable force-directed blob — the same engines as the
    branching-tree video), normalized into the unit square. Node name = image
    index. Returns None if the engine is unavailable or produced nothing.

    Both engines run Prism overlap-removal with a `-Gsep` margin so the
    point-nodes end up far enough apart that the (much larger) thumbnails we
    later draw on top don't pile up — this is what "spreads the tree out". twopi
    with overlap=prism is the organic spread seen in the branching-tree video
    (overlap=true would instead give pristine concentric rings == our analytic
    `radial`, so the two would look identical)."""
    import subprocess
    VR = "__root__"
    lines = ["graph G {", "  node [shape=point, width=0.02, height=0.02];", "  edge [len=0.4];"]
    if engine == "twopi":
        lines.append(f'  "{VR}";')                     # one hub so the forest of founders shares a center
    for i in range(n):
        lines.append(f'  "{i}";')                      # declare all (childless roots still get coords)
    for p, ch in enumerate(children):
        for c in ch:
            lines.append(f'  "{p}" -- "{c}";')
    if engine == "twopi":
        for r in roots:
            lines.append(f'  "{VR}" -- "{r}";')
    lines.append("}")
    cmd = [engine, "-Tplain", "-Goverlap=prism", "-Gsep=+9"]   # Prism de-overlap + margin -> spread (≈3.5s/3k nodes)
    if engine == "twopi":
        cmd += [f"-Groot={VR}", "-Granksep=1.2"]
    elif engine == "sfdp":
        cmd += ["-GK=1.4", "-Grepulsiveforce=2.0"]     # larger ideal edge length + stronger repulsion -> airier blob
    try:
        out = subprocess.run(cmd, input="\n".join(lines).encode(),
                             capture_output=True, timeout=600).stdout.decode()
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return None
    raw = [None] * n
    for line in out.splitlines():
        if line.startswith("node "):
            parts = line.split()
            name = parts[1].strip('"')
            if name == VR:
                continue
            raw[int(name)] = [float(parts[2]), float(parts[3])]
    if all(p is None for p in raw):
        return None
    for i in range(n):
        if raw[i] is None:
            raw[i] = [0.0, 0.0]
    return _normalize_xy(raw)


def phylogeny_layout(entries, n) -> dict:
    """Phylogeny 'tree of life' as a kind:scatter layout carrying THREE position
    variants — sfdp (graphviz force-directed, the default), twopi (graphviz
    Prism-spread rings), radial (analytic concentric rings) — over one shared
    parent->child edge set. The gallery shows a nested sub-toggle and morphs
    thumbnails between whichever variant is picked. Edges list parent->child so
    a renderer can draw the older parent on top (z-order by publication)."""
    children, roots = _build_forest(entries, n)
    leaf = _subtree_leaves(children, roots, n)
    parent = [None] * n
    for p, ch in enumerate(children):
        for c in ch:
            parent[c] = p
    edges = [[parent[i], i] for i in range(n) if parent[i] is not None]
    variants = {"radial": _radial_scatter_xy(children, roots, leaf, n)}
    for eng in ("twopi", "sfdp"):
        xy = _graphviz_scatter_xy(children, roots, n, eng)
        if xy is not None:
            variants[eng] = xy
    # sfdp first (and default); fall back to radial if graphviz is unavailable.
    order = [k for k in ("sfdp", "twopi", "radial") if k in variants]
    default = "sfdp" if "sfdp" in variants else "radial"
    return {"kind": "scatter", "edges": edges,
            "variants": variants, "variant_order": order, "default": default}


def encode_thumbs(images_dir: Path, out_dir: Path, n_keep: int,
                  force: bool = False, color: bool = True) -> int:
    """Convert each archive image to a small WebP thumb.

    Defaults to color (RGB) — many archive images do use color, and grayscale
    thumbs hid it. Pass color=False to flatten to grayscale ("L", ~30% smaller).
    Encodes only the first n_keep images (those covered by the chronological
    layout); any trailing unmatched images are skipped.
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    n_written = 0
    target = "RGB" if color else "L"
    pngs = sorted(images_dir.glob("img_*.png"))[:n_keep]
    for i, src in enumerate(pngs):
        dst = out_dir / (src.stem + ".webp")
        if dst.exists() and not force and dst.stat().st_mtime >= src.stat().st_mtime:
            continue
        img = Image.open(src); img.load()
        if img.mode != target:
            img = img.convert(target)
        img.save(dst, "WEBP", quality=80, method=6)
        n_written += 1
        if (i + 1) % 500 == 0:
            print(f"    encoded {i + 1}/{len(pngs)}")
    print(f"  encoded {n_written} new thumbs ({len(pngs)} total)")
    return len(pngs)


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("arc_seed", nargs="?", help="e.g. default_s4 (one of the canonical table arcs)")
    p.add_argument("--run", help="explicit sweep run-dir basename (bypasses the arc map; "
                                 "use for runs outside the results table, e.g. extra seeds / models)")
    p.add_argument("--out", help="explicit output lib dir (default: <ASSETS>/<token>_lib)")
    p.add_argument("--force", action="store_true")
    p.add_argument("--grayscale", action="store_true",
                   help="flatten thumbs to grayscale (default: color RGB)")
    args = p.parse_args()

    if args.run:
        # Explicit run dir: derive arc/seed from the name (arc may be None for
        # non-table runs, e.g. gemini-3 / flash-lite). siglip is skipped below if
        # the run has no cached embeddings.
        run_name = args.run
        cfg = parse_config(run_name)
        seed = cfg.get("seed")
        arc = canonical_arc(run_name, cfg)        # model-independent cell key
        token = run_name
    else:
        if not args.arc_seed:
            raise SystemExit("provide an <arc>_s<seed> token or --run <run-dir>")
        arc, seed = parse_arc_seed(args.arc_seed)
        if arc not in ARC_TO_RUN:
            raise SystemExit(f"unknown arc {arc!r}; known: {sorted(ARC_TO_RUN)}")
        run_name = f"{ARC_TO_RUN[arc]}_s{seed}"
        cfg = parse_config(run_name)
        token = args.arc_seed
    run = SWEEP / run_name
    if not run.is_dir():
        raise SystemExit(f"run dir not found: {run}")

    out_root = Path(args.out) if args.out else ASSETS / f"{token}_lib"
    print(f"[{token}]  run={run}\n  out={out_root}")

    # 1) chronological layout (defines our N: number of images).
    chrono_rc, chrono_dims, n_keep = chronological_layout(
        run / "archive" / "archive_grid.json")
    print(f"  chronological grid: {chrono_dims[0]} x {chrono_dims[1]} "
          f"({n_keep} entries)")

    # 2) SigLIP layout from cached embeddings (optional — some runs outside the
    #    results table were never embedded; the gallery greys out a missing sort).
    npz = run / "embeddings_openclip_SigLIP2-B-alignet.npz"
    siglip_rc = siglip_dims = None
    if npz.is_file():
        try:
            siglip_rc, siglip_dims = siglip_layout(npz, n_keep=n_keep)
            print(f"  siglip grid:        {siglip_dims[0]} x {siglip_dims[1]} "
                  f"({len(siglip_rc)} entries)")
        except Exception as e:                  # umap/rasterfairy unavailable -> skip the sort
            siglip_rc = siglip_dims = None
            print(f"  siglip grid:        SKIPPED ({type(e).__name__}: {e})")
    else:
        print(f"  siglip grid:        SKIPPED (no embeddings at {npz.name})")

    # 3) lineage-derived layouts (branched + ratings grids, radial phylogeny).
    entries = _aligned_entries(run / "archive" / "archive_metadata.json", n_keep)
    cols = chrono_dims[1]                       # reuse chronological column count
    branched = branched_layout(entries, n_keep, cols)
    ratings = ratings_layout(entries, n_keep, cols)
    phylogeny = phylogeny_layout(entries, n_keep)
    n_rated = sum(1 for e in entries if e.get("vlm_ratings"))
    print(f"  branched grid:      {branched['dims'][0]} x {branched['dims'][1]}")
    print(f"  ratings grid:       {ratings['dims'][0]} x {ratings['dims'][1]} "
          f"({n_rated}/{n_keep} rated)")
    print(f"  phylogeny scatter:  {len(phylogeny['edges'])} edges, "
          f"variants={phylogeny.get('variant_order')}")

    # 4) emit layout.json (images are identified by their published index i,
    #    i.e. filename img_{i+1:06d}.png).
    out_root.mkdir(parents=True, exist_ok=True)
    layout = {
        "arc": arc,
        "seed": seed,
        "model": cfg.get("model"),
        "n": n_keep,
        "thumb_px": 128,
        "filename_template": "img_{i06}.png",   # i is 1-based; thumbs are .webp
        "layouts": {
            "chronological": {"dims": chrono_dims, "rc": chrono_rc},
            "branched":      branched,
            "ratings":       ratings,
            "phylogeny":     phylogeny,
        },
    }
    if siglip_rc is not None:
        layout["layouts"]["siglip"] = {"dims": siglip_dims, "rc": siglip_rc}
    (out_root / "layout.json").write_text(json.dumps(layout) + "\n")
    print(f"  wrote layout.json ({(out_root / 'layout.json').stat().st_size} bytes)")

    # 4) encode per-image thumbs
    encode_thumbs(run / "archive" / "images", out_root / "thumbs",
                  n_keep=n_keep, force=args.force, color=not args.grayscale)

    # 5) total disk
    total = sum(p.stat().st_size for p in out_root.rglob("*") if p.is_file())
    print(f"\nDone. {out_root} -> {total/1e6:.1f} MB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
