/*
 * Unlicensed intellectual property of the University of Central Florida for
 * internal usage only. You may not distribute this code to anyone. You may
 * not use this code (as source or compiled) or information obtained from
 * this code without permission.
 *
 * Picbreeder Project
 * Evolutionary Complexity Research Group
 * School of Electrical Engineering and Computer Science
 * 2006-2007
 */

package client.tools;

import javax.swing.GroupLayout;
import javax.swing.JApplet;
import javax.swing.JPanel;
import javax.swing.GroupLayout.Alignment;

public class RenderApplet extends JApplet {
    
	public StandaloneRender renderer=new StandaloneRender();
    public String sid="402";
    /** Creates new form RendererFrame */
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">                          
    private void initComponents() {
        jFileChooser1 = new javax.swing.JFileChooser();
        jTextField1 = new javax.swing.JTextField(20);
        jLabel1 = new javax.swing.JLabel("Width");
        jTextField2 = new javax.swing.JTextField(20);
        jLabel2 = new javax.swing.JLabel("Height");
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField(20);
        jButton2 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField(20);
        jLabel3 = new javax.swing.JLabel("Save Path");
        jLabel4 = new javax.swing.JLabel("Genome ID");


        jButton1.setText("Render");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                render(evt);
            }
        });

        jButton2.setText("Browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectLocation(evt);
            }
        });


        JPanel panel=new JPanel();
        GroupLayout layout=new GroupLayout(panel);
        panel.setLayout(layout);
        layout.setAutoCreateGaps(true);
        layout.setAutoCreateContainerGaps(true);
        
        GroupLayout.SequentialGroup hGroup = layout.createSequentialGroup();
        
       hGroup.addGroup(layout.createParallelGroup().addComponent(jLabel1).addComponent(jLabel2).addComponent(jLabel3).addComponent(jButton2).addComponent(jLabel4).addComponent(jButton1));
       hGroup.addGroup(layout.createParallelGroup().addComponent(jTextField1).addComponent(jTextField2).addComponent(jTextField3).addComponent(jTextField4));
       layout.setHorizontalGroup(hGroup);
       
       GroupLayout.SequentialGroup vGroup = layout.createSequentialGroup();
       vGroup.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel1).addComponent(jTextField1));
      vGroup.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel2).addComponent(jTextField2));
      vGroup.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel3).addComponent(jTextField3));
      vGroup.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jButton2));
      vGroup.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jLabel4).addComponent(jTextField4));
      vGroup.addGroup(layout.createParallelGroup(Alignment.BASELINE).addComponent(jButton1));
      layout.setVerticalGroup(vGroup);
       
        
     /*   panel.add(jTextField1,BorderLayout.LINE_START);
        panel.add(jLabel1,BorderLayout.LINE_END);
        panel.add(jTextField2,BorderLayout.LINE_START);
        panel.add(jLabel2,BorderLayout.LINE_END);
        panel.add(jTextField3,BorderLayout.LINE_START);
        panel.add(jButton2,BorderLayout.LINE_END);
        panel.add(jTextField4,BorderLayout.LINE_START);
        panel.add(jLabel3,BorderLayout.LINE_END);*/
        
        
//        /panel.add(jLabel4,BorderLayout.CENTER);
        panel.add(jButton1);
        
        this.setContentPane(panel);
        //javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        //getContentPane().setLayout(layout);
        
    }// </editor-fold>                        

    private void render(java.awt.event.ActionEvent evt) {                        
        renderer.render(jTextField1.getText(),jTextField2.getText(),Integer.parseInt(jTextField4.getText()),jTextField3.getText());
    }                       

    private void selectLocation(java.awt.event.ActionEvent evt) {                                

        jFileChooser1.showSaveDialog(this);
        java.io.File file=jFileChooser1.getSelectedFile();
        if(file!=null)
        	jTextField3.setText(file.toString());
    }                               
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RendererFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration                  
    
	public RenderApplet()
	{
		super();
	}
	public void init()
	{
		initComponents();
		String genomeId=getParameter("id");
		if(genomeId!=null)
			jTextField4.setText(genomeId);
	}
	public void start()
	{
		
	}
}
